# Generated by Django 4.1.2 on 2022-11-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_productmodel_unitmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="unit",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
