# Generated by Django 4.1.2 on 2022-11-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cardcategorymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ManyToManyField(to="core.cardcategorymodel"),
        ),
    ]
