# Generated by Django 4.1.2 on 2022-11-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_stockmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.productmodel"
            ),
        ),
    ]
