# Generated by Django 4.1.2 on 2022-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cardcategorymodel_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmodel",
            name="phone_no",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
