# Generated by Django 4.1.2 on 2022-11-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_feedbackmodel_phone_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackmodel",
            name="phone_no",
        ),
    ]
