# Generated by Django 4.1.2 on 2022-11-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_addressmodel_name_addressmodel_phone_number"),
        ("core", "0008_remove_feedbackmodel_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=500)),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="CardCategoryModel",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="quantity",
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="product",
            field=models.ManyToManyField(to="core.productmodel"),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="quantity",
            field=models.ManyToManyField(to="core.stockmodel"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ManyToManyField(to="core.categorymodel"),
        ),
    ]
