# Generated by Django 4.1.2 on 2022-11-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_feedbackmodel_phone_no"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_name", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                ("district", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=32)),
                ("country", models.CharField(default="India", max_length=24)),
                ("postal_code", models.CharField(max_length=6)),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=15,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/user.png", upload_to="user/profile/image/"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("address", models.ManyToManyField(blank=True, to="user.addressmodel")),
                (
                    "card_type",
                    models.ManyToManyField(blank=True, to="core.cardcategorymodel"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
