# Generated by Django 4.1.2 on 2022-11-28 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_addressmodel_profilemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lattitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.locationmodel",
            ),
        ),
    ]
