# Generated by Django 4.1.2 on 2022-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_locationmodel_addressmodel_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="address",
            field=models.ManyToManyField(to="user.addressmodel"),
        ),
    ]
