# Generated by Django 4.1.2 on 2022-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profilemodel_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="phone_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
