# Generated by Django 4.1.2 on 2022-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_cardmodel_categorymodel_stockmodel_and_more"),
        ("user", "0005_addressmodel_name_addressmodel_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="address",
            field=models.ManyToManyField(blank=True, to="user.addressmodel"),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="card_type",
            field=models.ManyToManyField(blank=True, to="core.cardmodel"),
        ),
    ]
